export const DECLINE_REQUEST_DRIVER = 'DECLINE_REQUEST_DRIVER';
export const DECLINE_REQUEST_DRIVER_SUCCESS = 'DECLINE_REQUEST_DRIVER_SUCCESS';
export const DECLINE_REQUEST_DRIVER_FAILED = 'DECLINE_REQUEST_DRIVER_FAILED';
