export const DETAIL_REQUEST_SWITCH_ORDER = 'DETAIL_REQUEST_SWITCH_ORDER';
export const DETAIL_REQUEST_SWITCH_ORDER_SUCCESS =
  'DETAIL_REQUEST_SWITCH_ORDER_SUCCESS';
export const DETAIL_REQUEST_SWITCH_ORDER_FAILED =
  'DETAIL_REQUEST_SWITCH_ORDER_FAILED';
