export const ACCEPT_REQUEST_DRIVER = 'ACCEPT_REQUEST_DRIVER';
export const ACCEPT_REQUEST_DRIVER_SUCCESS = 'ACCEPT_REQUEST_DRIVER_SUCCESS';
export const ACCEPT_REQUEST_DRIVER_FAILED = 'ACCEPT_REQUEST_DRIVER_FAILED';
 