export const GET_AVAILABLE_DRIVER = 'GET_AVAILABLE_DRIVER';
export const GET_AVAILABLE_DRIVER_SUCCESS = 'GET_AVAILABLE_DRIVER_SUCCESS';
export const GET_AVAILABLE_DRIVER_FAILED = 'GET_AVAILABLE_DRIVER_FAILED';
export const SELECT_AVAILABLE_DRIVER = 'SELECT_AVAILABLE_DRIVER';
